services:
  server:
    build: ./server
    ports:
      - "8080:8000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
    restart: on-failure
    
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data/db:/data/db
